packages:
  - apps/*
  - packages/*

catalogs:
  better-auth:
    better-auth: latest
  prisma:
    prisma: latest

# Only allow these packages to run their build scripts
# All other packages with install scripts will be ignored
onlyBuiltDependencies:
  - '@prisma/engines'
  - prisma
  - esbuild
  - sharp
