packages:
  - apps/*
  - packages/*

catalogs:
  better-auth:
    better-auth: latest
  prisma:
    prisma: latest

ignoredBuiltDependencies:
  - '@prisma/engines'
  - core-js-pure
  - esbuild
  - prisma
  - sharp
  - unrs-resolver

onlyBuiltDependencies: '@prisma/engines prisma esbuild unrs-resolver'
