packages:
  - apps/*
  - packages/*

catalogs:
  better-auth:
    better-auth: latest
  prisma:
    prisma: latest
  vitest:
    vitest: latest
  typescript:
    typescript: ^5.9.3
    tslib: ^2.8.1
  react:
    '@types/react': ^19.2.10
    '@types/react-dom': ^19.2.3

# Only allow these packages to run their build scripts
# All other packages with install scripts will be ignored
onlyBuiltDependencies:
  - '@prisma/engines'
  - prisma
  - esbuild
  - sharp
