packages:
  - apps/*
  - packages/*

catalogs:
  better-auth:
    better-auth: ^1.6.23
  prisma:
    prisma: ^7.8.0
  react:
    '@types/react': ^19.2.17
    '@types/react-dom': ^19.2.3
  typescript:
    tslib: ^2.8.1
    typescript: ^5.9.3
  vitest:
    vitest: ^4.1.10

onlyBuiltDependencies:
  - '@prisma/engines'
  - prisma
  - esbuild
  - sharp
