export {
  // Schemas
  ProviderSourceSchema,
  HarmonizedArtistCreditSchema,
  HarmonizedTrackSchema,
  ReleaseTypeSchema,
  ReleaseStatusSchema,
  ArtworkTypeSchema,
  PartialDateSchema,
  HarmonizedReleaseSchema,
  ArtistTypeSchema,
  HarmonizedArtistSchema,
  // Types
  type ProviderSource,
  type HarmonizedArtistCredit,
  type HarmonizedTrack,
  type ReleaseType,
  type ReleaseStatus,
  type ArtworkType,
  type PartialDate,
  type HarmonizedRelease,
  type ArtistType,
  type HarmonizedArtist,
} from './types';

// Utility functions
export {
  formatDuration,
  formatPartialDate,
  formatArtistCredits,
  formatArtistNames,
  getPrimaryArtistName,
  formatTrackPosition,
  getFrontArtworkUrl,
} from './utils';

// Common components
export {
  PlatformBadge,
  PlatformBadgeList,
  ReleaseTypePill,
  getReleaseTypeLabel,
  getReleaseTypePluralLabel,
  releaseTypeLabels,
  releaseTypePluralLabels,
  MetadataTable,
  MetadataGrid,
  MetadataTableSkeleton,
  GridSkeleton,
  ListSkeleton,
  HeroSkeleton,
  PageSkeleton,
  InlineSkeleton,
  Artwork,
  PlatformProfileCard,
  PlatformProfileCardSkeleton,
  ProviderSyncStatus,
  type PlatformName,
  type PlatformBadgeProps,
  type PlatformBadgeListProps,
  type ReleaseTypePillProps,
  type MetadataItem,
  type MetadataTableProps,
  type MetadataGridProps,
  type MetadataTableSkeletonProps,
  type GridSkeletonProps,
  type ListSkeletonProps,
  type HeroSkeletonProps,
  type PageSkeletonProps,
  type InlineSkeletonProps,
  type ArtworkProps,
  type PlatformProfileCardProps,
  type PlatformProfileCardSkeletonProps,
  type PlatformProfile,
  type ProfileImage,
  type SubscriptionInfo,
  type FollowedArtist,
  type FollowedArtistsData,
  type ProfileError,
  type ProviderSyncStatusProps,
  type ProviderSyncStatusType,
} from './components/common';

// Track components
export {
  TrackArtwork,
  TrackCard,
  TrackCardSkeleton,
  TrackList,
  TrackListSkeleton,
  TrackDetails,
  TrackDetailsSkeleton,
  type TrackArtworkProps,
  type TrackCardProps,
  type TrackListProps,
  type TrackListSkeletonProps,
  type TrackDetailsProps,
} from './components/track';

// Artist components
export {
  ArtistCard,
  ArtistCardSkeleton,
  ArtistHeader,
  ArtistHeaderSkeleton,
  ArtistDiscography,
  ArtistDiscographySkeleton,
  ArtistListItem,
  ArtistListItemSkeleton,
  ArtistCredit,
  ArtistMention,
  type ArtistCardProps,
  type ArtistHeaderProps,
  type ArtistDiscographyProps,
  type ArtistDiscographySkeletonProps,
  type ArtistListItemProps,
  type ArtistListItemSkeletonProps,
  type ArtistCreditProps,
  type ArtistMentionProps,
} from './components/artist';

// Album components
export {
  AlbumArtwork,
  AlbumArtworkSkeleton,
  AlbumCard,
  AlbumCardSkeleton,
  AlbumListItem,
  AlbumListItemSkeleton,
  AlbumTrackList,
  AlbumTrackListSkeleton,
  AlbumDetails,
  AlbumDetailsSkeleton,
  type AlbumArtworkProps,
  type AlbumArtworkSkeletonProps,
  type AlbumCardProps,
  type AlbumListItemProps,
  type AlbumListItemSkeletonProps,
  type AlbumTrackListProps,
  type AlbumTrackListSkeletonProps,
  type AlbumDetailsProps,
} from './components/album';

// Interactions
export {
  // Provider
  HarmonyInteractionProvider,
  useHarmonyInteraction,
  HarmonyInteractionContext,
  // Interactive Wrapper
  InteractiveWrapper,
  // Menus
  EntityMenu,
  TrackContextMenu,
  AlbumContextMenu,
  ArtistContextMenu,
  ProviderActionsGroup,
  ProviderMenuItem,
  // Previews
  EntityPreview,
  TrackHoverPreview,
  AlbumHoverPreview,
  ArtistHoverPreview,
  // Types
  type EntityType,
  type Platform,
  type HarmonizedEntity,
  type MenuAction,
  type PreviewMode,
  type PreviewContent,
  type EntityPreviewContentProps,
  type HarmonyInteractionConfig,
  type HarmonyInteractionContextValue,
  type InteractiveWrapperProps,
  type HarmonyInteractionProviderProps,
  type EntityMenuProps,
  type TrackContextMenuProps,
  type AlbumContextMenuProps,
  type ArtistContextMenuProps,
  type ProviderActionsGroupProps,
  type ProviderMenuItemProps,
  type EntityPreviewProps,
  type TrackHoverPreviewProps,
  type AlbumHoverPreviewProps,
  type ArtistHoverPreviewProps,
  // Provider action types
  type ProviderActionType,
  type ProviderName,
  type ProviderAction,
  type ProviderActions,
  type EnabledProvider,
} from './interactions';

// Provider Icons
export {
  // Base component
  ProviderIcon,
  PROVIDER_METADATA,
  getSupportedProviders,
  isProviderSupported,
  getProviderIconMetadata,
  // Provider-specific components
  SpotifyIcon,
  AppleMusicIcon,
  TidalIcon,
  // Metadata
  spotifyIconMetadata,
  appleMusicIconMetadata,
  tidalIconMetadata,
  // URL helpers
  getSpotifyIconUrl,
  getAppleMusicIconUrl,
  getTidalIconUrl,
  // Types
  type Provider as IconProvider,
  type IconVariant,
  type IconColor,
  type IconSize,
  type IconFormat,
  type BaseIconProps,
  type ProviderIconProps,
  type ProviderSpecificIconProps,
  type ProviderIconMetadata,
  type SpotifyIconProps,
  type AppleMusicIconProps,
  type TidalIconProps,
  // Constants
  SIZE_PRESETS,
  PROVIDER_LABELS,
  PROVIDER_BRAND_COLORS,
  resolveSize,
  resolveFillColor,
} from './icons';
