import {
  ArrowRight,
  Compass,
  Database,
  Home,
  LogIn,
  Search,
  Rss,
  Settings,
  User,
  CloudSync,
  Users,
} from 'lucide-react';

export const ROUTES = {
  home: {
    href: '/',
    label: 'Home',
    icon: Home,
    protected: false,
    isAdmin: false,
  },
  search: {
    href: '/search',
    label: 'Search',
    icon: Search,
    protected: true,
    isAdmin: false,
  },
  feed: {
    href: '/feed',
    label: 'Feed',
    icon: Rss,
    protected: true,
    isAdmin: false,
  },
  explore: {
    href: '/explore',
    label: 'Explore',
    icon: Compass,
    protected: true,
    isAdmin: false,
  },
  users: {
    href: '/users',
    label: 'Users',
    icon: Users,
    protected: true,
    isAdmin: false,
  },
  profile: {
    href: '/profile',
    label: 'Profile',
    icon: User,
    protected: true,
    isAdmin: false,
  },
  settings: {
    href: '/settings',
    label: 'Settings',
    icon: Settings,
    protected: true,
    isAdmin: false,
  },
  signup: {
    href: '/signup',
    label: 'Signup',
    icon: ArrowRight,
    protected: false,
    isAdmin: false,
  },
  login: {
    href: '/login',
    label: 'Login',
    icon: LogIn,
    protected: false,
    isAdmin: false,
  },
  db: {
    href: '/admin/db',
    label: 'Database',
    icon: Database,
    protected: true,
    isAdmin: true,
  },
  harmony: {
    href: '/admin/harmony',
    label: 'Harmony',
    icon: CloudSync,
    protected: true,
    isAdmin: true,
  },
  adminUsers: {
    href: '/admin/users',
    label: 'Users',
    icon: Users,
    protected: true,
    isAdmin: true,
  },
} as const;
